import React, { useState } from 'react';
import { 
  X, 
  Calculator, 
  Sparkles, 
  Check, 
  Send, 
  FileText, 
  Download, 
  Clock, 
  Layers, 
  ShieldCheck, 
  DollarSign, 
  Cpu, 
  ArrowRight,
  Printer,
  Copy,
  Building2,
  Mail,
  User
} from 'lucide-react';
import { ProjectQuotation } from '../types';
import { MillerzLogo } from './MillerzLogo';

interface QuoteGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
  defaultEmail?: string;
}

export const QuoteGeneratorModal: React.FC<QuoteGeneratorModalProps> = ({
  isOpen,
  onClose,
  defaultEmail = ''
}) => {
  if (!isOpen) return null;

  // Form State
  const [clientName, setClientName] = useState('');
  const [companyName, setCompanyName] = useState('');
  const [email, setEmail] = useState(defaultEmail || '');
  const [projectType, setProjectType] = useState<any>('Web Platform');
  const [selectedFeatures, setSelectedFeatures] = useState<string[]>([
    'Authentication & User Roles',
    'Responsive Next.js 16 UI',
    'API Proxying & Secret Security'
  ]);
  const [targetTimeline, setTargetTimeline] = useState('1-2 months');
  const [budgetRange, setBudgetRange] = useState('$10,000 - $25,000');
  const [projectNotes, setProjectNotes] = useState('');

  // Result State
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedQuote, setGeneratedQuote] = useState<ProjectQuotation | null>(null);
  const [copiedSuccess, setCopiedSuccess] = useState(false);
  const [submittedSuccess, setSubmittedSuccess] = useState(false);

  const availableFeatures = [
    { id: 'auth', label: 'Authentication & User Roles (RBAC)', category: 'Core' },
    { id: 'next16', label: 'Responsive Next.js 16 & Motion UI', category: 'Frontend' },
    { id: 'mobile', label: 'iOS & Android Mobile App (React Native)', category: 'Mobile' },
    { id: 'ai', label: 'Gemini 3.6 AI Engine & Agent Workflows', category: 'AI' },
    { id: 'realtime', label: 'Real-Time WebSockets & Push Alerts', category: 'Backend' },
    { id: 'payments', label: 'Stripe / Payment Subscription Gateway', category: 'E-Commerce' },
    { id: 'analytics', label: 'Analytics Dashboard & Reporting', category: 'Data' },
    { id: 'cloud', label: 'Cloud Run CI/CD & SSL Infrastructure', category: 'DevOps' }
  ];

  const toggleFeature = (label: string) => {
    if (selectedFeatures.includes(label)) {
      setSelectedFeatures(selectedFeatures.filter(f => f !== label));
    } else {
      setSelectedFeatures([...selectedFeatures, label]);
    }
  };

  const handleGenerateQuote = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!clientName || !email) return;

    setIsGenerating(true);
    setGeneratedQuote(null);

    try {
      const res = await fetch('/api/quote/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          clientName,
          companyName,
          email,
          projectType,
          selectedFeatures,
          targetTimeline,
          budgetRange,
          projectNotes
        })
      });

      const data = await res.json();
      if (data.status === 'success' && data.quotation) {
        setGeneratedQuote(data.quotation);
      }
    } catch (e) {
      console.error("Failed to generate quotation:", e);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopyProposal = () => {
    if (!generatedQuote) return;
    const text = `MILLERZ TECHNOLOGIES - OFFICIAL PROJECT QUOTATION\n` +
      `Quote Code: ${generatedQuote.quotationId}\n` +
      `Client: ${generatedQuote.clientName} (${generatedQuote.companyName || 'Independent'})\n` +
      `Project Type: ${generatedQuote.projectType}\n` +
      `Estimated Investment Range: $${generatedQuote.estimatedPriceRange.min.toLocaleString()} - $${generatedQuote.estimatedPriceRange.max.toLocaleString()} USD\n` +
      `Timeline: ${generatedQuote.targetTimeline}\n\n` +
      `Architecture Proposal:\n${generatedQuote.architectureProposal}\n\n` +
      `Generated by Millerz Technologies (contact@millerz.tech)`;

    navigator.clipboard.writeText(text);
    setCopiedSuccess(true);
    setTimeout(() => setCopiedSuccess(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/85 backdrop-blur-md overflow-y-auto animate-next-enter">
      <div 
        onClick={(e) => e.stopPropagation()}
        className="relative w-full max-w-3xl bg-[#0B0E0C] border border-[#212E25] rounded-3xl shadow-2xl overflow-hidden my-6 flex flex-col max-h-[90vh]"
      >
        {/* Header with Millerz Logo */}
        <div className="px-6 py-4 border-b border-[#212E25] bg-[#131A15] flex items-center justify-between">
          <div className="flex items-center gap-3">
            <MillerzLogo size="sm" />
            <div className="hidden sm:flex items-center gap-2 pl-3 border-l border-emerald-900/60 font-mono text-xs">
              <span className="px-2 py-0.5 rounded bg-[#25432D] text-[#C29845] font-bold">
                INSTANT QUOTATION ENGINE
              </span>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 rounded-xl bg-[#1C261F] border border-[#2B3B30] text-gray-400 hover:text-white transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto flex-1 text-xs space-y-6">
          
          {!generatedQuote && !isGenerating && (
            /* STEP 1: FORM INPUTS */
            <form onSubmit={handleGenerateQuote} className="space-y-6">
              
              <div className="p-4 rounded-2xl bg-gradient-to-r from-[#16251A] via-[#1A1813] to-[#1F1713] border border-[#2D5237] space-y-2">
                <div className="flex items-center gap-2 text-[#C29845] font-mono font-bold text-sm">
                  <Calculator className="w-4 h-4 text-[#E06332]" />
                  <span>Get an Official AI Project Cost & Technical Proposal</span>
                </div>
                <p className="text-gray-300 text-xs">
                  Select your desired web app, mobile, or cloud requirements below. Millerz Technologies AI Architect will immediately compute an itemized scope breakdown, timeline, and pricing model.
                </p>
              </div>

              {/* Client Info Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div className="space-y-1">
                  <label className="font-mono text-gray-300 font-semibold uppercase text-[10px] flex items-center gap-1">
                    <User className="w-3 h-3 text-[#E06332]" />
                    <span>Your Full Name *</span>
                  </label>
                  <input
                    type="text"
                    required
                    value={clientName}
                    onChange={(e) => setClientName(e.target.value)}
                    placeholder="e.g. Alex Miller"
                    className="w-full bg-[#131A15] border border-[#212E25] rounded-xl py-2 px-3 text-xs text-white placeholder-gray-600 focus:outline-none focus:border-[#E06332]"
                  />
                </div>

                <div className="space-y-1">
                  <label className="font-mono text-gray-300 font-semibold uppercase text-[10px] flex items-center gap-1">
                    <Building2 className="w-3 h-3 text-[#C29845]" />
                    <span>Company / Organization</span>
                  </label>
                  <input
                    type="text"
                    value={companyName}
                    onChange={(e) => setCompanyName(e.target.value)}
                    placeholder="e.g. Millerz Tech Partner"
                    className="w-full bg-[#131A15] border border-[#212E25] rounded-xl py-2 px-3 text-xs text-white placeholder-gray-600 focus:outline-none focus:border-[#C29845]"
                  />
                </div>

                <div className="space-y-1">
                  <label className="font-mono text-gray-300 font-semibold uppercase text-[10px] flex items-center gap-1">
                    <Mail className="w-3 h-3 text-[#345D3F]" />
                    <span>Email Address *</span>
                  </label>
                  <input
                    type="email"
                    required
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="alex@millerz.tech"
                    className="w-full bg-[#131A15] border border-[#212E25] rounded-xl py-2 px-3 text-xs text-white placeholder-gray-600 focus:outline-none focus:border-[#345D3F]"
                  />
                </div>
              </div>

              {/* Project Type */}
              <div className="space-y-2">
                <label className="font-mono text-gray-300 font-bold uppercase tracking-wider text-[11px] block">
                  Project Classification
                </label>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                  {[
                    { id: 'Web Platform', label: 'Web Platform (Next.js 16)' },
                    { id: 'Mobile App', label: 'Mobile App (iOS/Android)' },
                    { id: 'AI & Cloud System', label: 'AI & Cloud System' },
                    { id: 'Enterprise Full-Stack', label: 'Enterprise Full-Stack' },
                    { id: 'Design System & UI', label: 'Design System & UI' }
                  ].map((pt) => (
                    <button
                      type="button"
                      key={pt.id}
                      onClick={() => setProjectType(pt.id as any)}
                      className={`p-3 rounded-xl font-mono text-xs border text-left transition ${
                        projectType === pt.id 
                          ? 'bg-[#25432D] border-[#C85223] text-white font-bold shadow-md shadow-[#C85223]/20' 
                          : 'bg-[#131A15] border-[#212E25] text-gray-400 hover:text-gray-200'
                      }`}
                    >
                      {pt.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Feature Checklist */}
              <div className="space-y-2">
                <label className="font-mono text-gray-300 font-bold uppercase tracking-wider text-[11px] block">
                  Required Modules & Capabilities
                </label>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {availableFeatures.map((feat) => {
                    const isSelected = selectedFeatures.includes(feat.label);
                    return (
                      <button
                        type="button"
                        key={feat.id}
                        onClick={() => toggleFeature(feat.label)}
                        className={`p-2.5 rounded-xl font-mono text-xs border text-left transition flex items-center justify-between ${
                          isSelected 
                            ? 'bg-[#1D2B20] border-[#345D3F] text-[#C29845] font-semibold' 
                            : 'bg-[#131A15] border-[#212E25] text-gray-400 hover:border-gray-700'
                        }`}
                      >
                        <span>{feat.label}</span>
                        {isSelected && <Check className="w-4 h-4 text-[#E06332]" />}
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Timeline & Budget Parameters */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="font-mono text-gray-300 font-bold uppercase tracking-wider text-[11px] block">
                    Target Delivery Timeline
                  </label>
                  <div className="grid grid-cols-3 gap-2">
                    {['2-4 weeks', '1-2 months', '3-6 months'].map((t) => (
                      <button
                        type="button"
                        key={t}
                        onClick={() => setTargetTimeline(t)}
                        className={`py-2 rounded-xl font-mono text-xs border transition ${
                          targetTimeline === t 
                            ? 'bg-[#C85223]/20 border-[#C85223] text-[#E06332] font-bold' 
                            : 'bg-[#131A15] border-[#212E25] text-gray-400'
                        }`}
                      >
                        {t}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="space-y-2">
                  <label className="font-mono text-gray-300 font-bold uppercase tracking-wider text-[11px] block">
                    Estimated Budget Bracket
                  </label>
                  <select
                    value={budgetRange}
                    onChange={(e) => setBudgetRange(e.target.value)}
                    className="w-full bg-[#131A15] border border-[#212E25] rounded-xl py-2 px-3 text-xs text-white font-mono focus:outline-none focus:border-[#C29845]"
                  >
                    <option value="$5,000 - $10,000">$5,000 - $10,000 USD (Starter MVP)</option>
                    <option value="$10,000 - $25,000">$10,000 - $25,000 USD (Standard Production)</option>
                    <option value="$25,000 - $50,000">$25,000 - $50,000 USD (Enterprise Scale)</option>
                    <option value="$50,000+">$50,000+ USD (Custom Architecture)</option>
                  </select>
                </div>
              </div>

              {/* Project Notes */}
              <div className="space-y-1">
                <label className="font-mono text-gray-300 font-bold uppercase tracking-wider text-[11px] block">
                  Additional Notes or Specific Feature Requests
                </label>
                <textarea
                  rows={2}
                  value={projectNotes}
                  onChange={(e) => setProjectNotes(e.target.value)}
                  placeholder="e.g. Needs Next.js 16 smooth animations, Dark mode UI, and PostgreSQL database..."
                  className="w-full bg-[#131A15] border border-[#212E25] rounded-xl p-3 text-xs text-white placeholder-gray-600 focus:outline-none focus:border-[#C85223]"
                />
              </div>

              <button
                type="submit"
                className="w-full py-3.5 rounded-2xl bg-gradient-to-r from-[#25432D] via-[#C85223] to-[#A88238] hover:opacity-95 text-white font-mono font-bold text-xs shadow-xl shadow-[#C85223]/20 transition flex items-center justify-center gap-2"
              >
                <Sparkles className="w-4 h-4 text-white" />
                <span>Generate Instant Millerz AI Technical Quotation</span>
              </button>

            </form>
          )}

          {/* STEP 2: GENERATING SPINNER */}
          {isGenerating && (
            <div className="py-20 text-center space-y-4 animate-next-enter">
              <div className="relative w-16 h-16 mx-auto">
                <div className="absolute inset-0 rounded-2xl bg-gradient-to-tr from-[#25432D] via-[#C85223] to-[#A88238] animate-spin opacity-80 blur-sm"></div>
                <div className="relative w-16 h-16 rounded-2xl bg-[#0B0E0C] border border-[#212E25] flex items-center justify-center">
                  <Cpu className="w-8 h-8 text-[#E06332] animate-pulse" />
                </div>
              </div>
              <div>
                <h4 className="font-mono font-bold text-white text-sm">
                  Computing Millerz AI Technical Quotation...
                </h4>
                <p className="text-gray-400 text-xs mt-1">
                  Synthesizing architecture proposal, itemized scope hours, and delivery milestones.
                </p>
              </div>
            </div>
          )}

          {/* STEP 3: RESULT PRESENTATION */}
          {generatedQuote && !isGenerating && (
            <div className="space-y-6 animate-next-enter">
              
              {/* Proposal Banner */}
              <div className="p-5 rounded-2xl bg-gradient-to-r from-[#1C2C20] via-[#2A1811] to-[#241D10] border border-[#C85223]/60 space-y-3">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-[#212E25] pb-3">
                  <div>
                    <span className="text-[10px] font-mono uppercase tracking-widest text-[#C29845]">
                      OFFICIAL QUOTATION CODE
                    </span>
                    <h3 className="font-mono font-black text-xl text-white">
                      {generatedQuote.quotationId}
                    </h3>
                  </div>
                  <div className="text-right">
                    <span className="text-[10px] font-mono uppercase tracking-widest text-gray-400">
                      ESTIMATED INVESTMENT RANGE
                    </span>
                    <div className="font-mono font-extrabold text-lg text-[#E06332]">
                      ${generatedQuote.estimatedPriceRange.min.toLocaleString()} – ${generatedQuote.estimatedPriceRange.max.toLocaleString()} USD
                    </div>
                  </div>
                </div>

                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-[11px] font-mono">
                  <div>
                    <span className="text-gray-500 block">CLIENT</span>
                    <span className="text-gray-200 font-bold">{generatedQuote.clientName}</span>
                  </div>
                  <div>
                    <span className="text-gray-500 block">PROJECT</span>
                    <span className="text-gray-200 font-bold">{generatedQuote.projectType}</span>
                  </div>
                  <div>
                    <span className="text-gray-500 block">TIMELINE</span>
                    <span className="text-gray-200 font-bold">{generatedQuote.targetTimeline}</span>
                  </div>
                  <div>
                    <span className="text-gray-500 block">VALIDITY</span>
                    <span className="text-emerald-400 font-bold">{generatedQuote.validityDays} Days</span>
                  </div>
                </div>
              </div>

              {/* Architecture Blueprint */}
              <div className="p-4 rounded-2xl bg-[#131A15] border border-[#212E25] space-y-2">
                <div className="flex items-center gap-2 font-mono font-bold text-white uppercase tracking-wider text-[11px]">
                  <Layers className="w-4 h-4 text-[#345D3F]" />
                  <span>Technical Architecture Blueprint</span>
                </div>
                <p className="text-gray-300 text-xs leading-relaxed font-sans">
                  {generatedQuote.architectureProposal}
                </p>
                <div className="flex flex-wrap gap-1.5 pt-2">
                  {generatedQuote.recommendedTechStack.map((tech) => (
                    <span key={tech} className="px-2 py-0.5 rounded-lg bg-[#1C2A20] border border-[#2B4732] text-[#C29845] font-mono text-[10px]">
                      {tech}
                    </span>
                  ))}
                </div>
              </div>

              {/* Itemized Scope Breakdown */}
              <div className="space-y-3">
                <h4 className="font-mono font-bold text-white uppercase tracking-wider text-xs flex items-center gap-2">
                  <FileText className="w-4 h-4 text-[#E06332]" />
                  <span>Itemized Module & Cost Breakdown</span>
                </h4>
                <div className="space-y-2">
                  {generatedQuote.itemizedScope.map((item, idx) => (
                    <div key={idx} className="p-3.5 rounded-xl bg-[#131A15] border border-[#212E25] flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                      <div>
                        <span className="font-mono font-bold text-white text-xs">{item.moduleName}</span>
                        <p className="text-[#9CA3AF] text-[11px] font-sans mt-0.5">{item.description}</p>
                      </div>
                      <div className="flex items-center gap-4 shrink-0 font-mono text-xs">
                        <span className="text-gray-400">{item.estimatedHours} hrs</span>
                        <span className="text-[#E06332] font-bold">${item.cost.toLocaleString()}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Phased Delivery Milestones */}
              <div className="space-y-3">
                <h4 className="font-mono font-bold text-white uppercase tracking-wider text-xs flex items-center gap-2">
                  <Clock className="w-4 h-4 text-[#C29845]" />
                  <span>Phased Delivery Milestones</span>
                </h4>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                  {generatedQuote.deliveryMilestones.map((ms, idx) => (
                    <div key={idx} className="p-3 rounded-xl bg-[#131A15] border border-[#212E25] space-y-1">
                      <span className="font-mono font-bold text-[#C29845] text-[11px] block">{ms.phase}</span>
                      <span className="text-gray-400 text-[10px] font-mono block">Estimated duration: {ms.weeks} week(s)</span>
                      <p className="text-gray-300 text-[11px] font-sans">{ms.deliverables}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Actions Footer inside modal */}
              <div className="pt-4 border-t border-[#212E25] flex flex-wrap items-center justify-between gap-3">
                <button
                  type="button"
                  onClick={() => setGeneratedQuote(null)}
                  className="px-4 py-2 rounded-xl bg-[#1C261F] border border-[#2B3B30] text-gray-300 font-mono text-xs hover:text-white"
                >
                  Edit Requirement Parameters
                </button>

                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={handleCopyProposal}
                    className="px-4 py-2 rounded-xl bg-[#25432D] hover:bg-[#345D3F] text-white font-mono text-xs font-bold transition flex items-center gap-1.5"
                  >
                    {copiedSuccess ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                    <span>{copiedSuccess ? 'Copied!' : 'Copy Proposal'}</span>
                  </button>

                  <button
                    type="button"
                    onClick={() => {
                      setSubmittedSuccess(true);
                      setTimeout(() => setSubmittedSuccess(false), 3000);
                    }}
                    className="px-5 py-2 rounded-xl bg-gradient-to-r from-[#C85223] to-[#E06332] hover:opacity-90 text-white font-mono text-xs font-bold shadow-lg shadow-[#C85223]/20 transition flex items-center gap-1.5"
                  >
                    <Send className="w-3.5 h-3.5" />
                    <span>{submittedSuccess ? 'Submitted to Sales!' : 'Submit to Millerz Technologies'}</span>
                  </button>
                </div>
              </div>

            </div>
          )}

        </div>

      </div>
    </div>
  );
};
